use_frameworks!

target 'SecureQueue_Example' do
  pod 'SecureQueue', :path => '../'
  pod 'OMHClient', :path => '../../OMHClient'

  target 'SecureQueue_Tests' do
    inherit! :search_paths


  end
end
